### ISSUE TITLE
Botty not working for char that didn't beat normal Baal (nightmare unlocked)

### ISSUE THREAD

**Issue by jagarop** [aeon0/botty#140]
**Botty Version**
#138

**Describe the bug**
Botty not working for char that didn't beat normal Baal (nightmare unlocked)

**To Reproduce**
1. Try to start with char that doesn't have nightmare unlocked, with normal setting on .ini

**Logs**
```
[2021-11-27 19:22:48,232] INFO       Searching for window offsets. Make sure D2R is in focus and you are on the hero selection screen
[2021-11-27 19:22:48,769] DEBUG      Set offsets: left 640px, top 340px
[2021-11-27 19:22:49,438] INFO       Setting up Sorceress
[2021-11-27 19:22:49,454] INFO       Starting game #1
[2021-11-27 19:22:49,455] DEBUG      Waiting for Template D2_LOGO_HS
[2021-11-27 19:22:49,507] DEBUG      Found Play Btn
[2021-11-27 19:22:49,796] DEBUG      Searching for normal Btn...
[2021-11-27 19:22:50,936] DEBUG      Waiting for Template NORMAL_BTN
[2021-11-27 19:22:59,543] DEBUG      Could not find btn, try from start again
```

**Additional info**
seems like this code was supposed to handle it, but it doesn't

```
while 1:
            # edge case: if a player hasn't unlocked nightmare difficulty, there won't be an option to select difficulty after clicking play button
            wait(0.75,1.25)
            if self._template_finder.search("LOADING", self._screen.grab())[0]:
                Logger.debug("On loading screen, nightmare not unlocked")
                return True

            found, pos = self._template_finder.search_and_wait("NORMAL_BTN", roi=self._config.ui_roi["normal_btn"], time_out=8)

            if not found:
                Logger.debug("Could not find btn, try from start again")
                return self.start_game()

            x, y = self._screen.convert_screen_to_monitor((self._config.ui_pos[f"{difficulty}_x"], self._config.ui_pos[f"{difficulty}_y"]))
            Logger.debug(f"Found {difficulty} Btn -> clicking it")
            mouse.move(x, y, randomize=[50, 9], delay_factor=[1.0, 1.8])
            wait(0.15, 0.2)
            mouse.click(button="left")
            break
```

**Comment by mgleed** [comment]
This should be easily solved once #125 is merged. should be ready soon

**Comment by mgleed** [comment]
Should be resolved on latest master, please test it out and let me know. @jagarop

**Comment by aeon0** [comment]
I tested it. Worked

**Comment by jagarop** [comment]
Still have this issue here with current version

https://youtu.be/eytEHsymR5o

**Comment by mgleed** [comment]
After this fix I added an ROI cuz of false button detections on left side of screen; however, I didn't include the LOADING template area in the ROI so the issue re-emerged. Now fixed with #249
