### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by offerduo** [aeon0/botty#580]
After synching with lastest code, I am getting the following errors while char exits:

[2022-02-22 17:23:39,403] INFO       Run Shenk
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\<usr>\d2r\botty\src\bot.py", line 153, in start
    self.trigger_or_stop('init')
  File "C:\Users\<usr>\d2r\botty\src\bot.py", line 173, in trigger_or_stop
    self.trigger(name, **kwargs)
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 899, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 401, in trigger
    return self.machine._process(func)
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1201, in _process
    self._transition_queue[0]()
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 426, in _trigger
    return self._process(event_data)
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 435, in _process
    if trans.execute(event_data):
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 272, in execute
    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1123, in callbacks
    self.callback(func, event_data)
  File "C:\Users\<usr>\Miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1144, in callback
    func(*event_data.args, **event_data.kwargs)
  File "C:\Users\<usr>\d2r\botty\src\bot.py", line 366, in on_end_game
    view.save_and_exit()
  File "C:\Users\<usr>\d2r\botty\src\ui_components\view.py", line 63, in save_and_exit
    if click_save_exit(exit_button):
  File "C:\Users\<usr>\d2r\botty\src\ui_components\view.py", line 47, in click_save_exit
    select_screen_object_match(match, delay_factor=(0.1, 0.3))
  File "C:\Users\<usr>\d2r\botty\src\ui\ui_manager.py", line 202, in select_screen_object_match
    mouse.move(*convert_screen_to_monitor(match.center), delay_factor=delay_factor)
  File "C:\Users\<usr>\d3r\botty\src\screen.py", line 25, in convert_screen_to_monitor
    x = screen_coord[0] + monitor_roi["left"]
TypeError: 'NoneType' object is not subscriptable

**Comment by offerduo** [comment]
I've tried on a different pc it's working well. Guess it's related to my low-end configuration.

Can we do something like disable the fancy pattern recognition for low-end pc?

**Comment by mgleed** [comment]
> I've tried on a different pc it's working well. Guess it's related to my low-end configuration.
> 
> Can we do something like disable the fancy pattern recognition for low-end pc?

This should be fixed on latest master, try again on the PC that wasn't working

**Comment by offerduo** [comment]
> > I've tried on a different pc it's working well. Guess it's related to my low-end configuration.
> > Can we do something like disable the fancy pattern recognition for low-end pc?
> 
> This should be fixed on latest master, try again on the PC that wasn't working

After syncing with latest code, the trace is gone. But 'exit' still doesn't work for me:

The 'menu' appears for  a very short time then disappears, leaving char stay in the game.
While the 'debug' shows:

Starting game #2 
Waiting for templates: , etc.

**Comment by mgleed** [comment]
> > > I've tried on a different pc it's working well. Guess it's related to my low-end configuration.
> > > Can we do something like disable the fancy pattern recognition for low-end pc?
> > 
> > 
> > This should be fixed on latest master, try again on the PC that wasn't working
> 
> After syncing with latest code, the trace is gone. But 'exit' still doesn't work for me:
> 
> The 'menu' appears for a very short time then disappears, leaving char stay in the game. While the 'debug' shows:
> 
> Starting game #2 Waiting for templates: , etc.

Could you give more detail? Perhaps video?

**Comment by offerduo** [comment]
[Video at the end of a game](https://www.dropbox.com/s/6b4d5d4pit7q955/Issue%23580_video.mov?dl=0)

Related debug:

```
[0.7.1-dev 2022-03-10 21:24:38,637] INFO       Run Eldritch
[0.7.1-dev 2022-03-10 21:24:38,637] DEBUG      Traverse from a5_town_start to a5_wp
[0.7.1-dev 2022-03-10 21:24:41,472] DEBUG      Select A5_WP (90.9% confidence)
[0.7.1-dev 2022-03-10 21:24:46,136] DEBUG      Waiting for templates: ['ELDRITCH_0', 'ELDRITCH_START']
[0.7.1-dev 2022-03-10 21:24:46,401] DEBUG      Found Match: ELDRITCH_START (96.4% confidence)
[0.7.1-dev 2022-03-10 21:24:46,486] INFO       Health Manager is now active
[0.7.1-dev 2022-03-10 21:25:02,222] INFO       End game. Elapsed time: 112.36s
[0.7.1-dev 2022-03-10 21:25:02,684] INFO       Starting game #2
[0.7.1-dev 2022-03-10 21:25:02,685] DEBUG      Waiting for templates: ['MAIN_MENU_TOP_LEFT', 'MAIN_MENU_TOP_LEFT_DARK', 'A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.1-dev 2022-03-10 21:25:41,894] INFO       Force Exit
[0.7.1-dev 2022-03-10 21:25:42,747] DEBUG      Detect window thread stopped
Restored D2R window visibility
```

**Comment by D2RLegit** [comment]
Are you running shenk as well? Looks like your trying to run eld only which it might be glitching it.

**Comment by offerduo** [comment]
Yes I do run both. And I only captured the Eldritch part for video and debug.

**Comment by mgleed** [comment]
Will look into this @offerduo. I can't identify yet what's causing the issue but it just might require reworking the save/exit logic.

**Comment by mgleed** [comment]
@offerduo try out latest master, see if most recent PR helped

**Comment by offerduo** [comment]
@mgleed After picking up the latest code, the login/logout works perfectly for me on my laptop.
Thanks for working on it.
